# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psd',
            name='Freq_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='psd',
            name='PSD_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
