# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSD', '0002_auto_20160613_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='psd',
            name='Freq_svg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='psd',
            name='PSD_svg',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
